services:
  - type: web
    name: shop-ararat-api
    env: python
    buildCommand: pip install -r python_analytics/requirements.txt
    startCommand: python python_analytics/api_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
    plan: free 